"use client"

import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Provider } from "react-redux"
import store from "@/store/store"
import { ThemeProvider } from "@mui/material/styles"
import theme from "@/theme/theme"
import AppProvider from "@/hoc/AppProvider"
import { CssBaseline } from "@mui/material"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider store={store}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <AppProvider>{children}</AppProvider>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  )
}
