export { default as loginSchema } from "./loginSchema"
export { default as resetSchema } from "./resetSchema"
// export { default as doctorSchema } from "./doctorSchema"
// export { default as updateProfileSchema } from "./updateProfileSchema"
// export { default as updatePassSchema } from "./updatePassSchema"
// export { default as patientSchema } from "./patientSchema"
export { default as classificationSchema } from "./classificationSchema"

// Export all form types
export type { LoginFormValues } from "./loginSchema"
export type { ResetFormValues } from "./resetSchema"
// export type { DoctorFormValues } from "./doctorSchema"
// export type { UpdateProfileFormValues } from "./updateProfileSchema"
// export type { UpdatePassFormValues } from "./updatePassSchema"
// export type { PatientFormValues } from "./patientSchema"
export type { ClassificationFormValues } from "./classificationSchema"
